### ISSUE TITLE
Incorrect Python Script in Web tutorial (developerWorks)

### ISSUE THREAD

**Issue by knurherb** [IBM/intro-to-docker-lab#2]
The python script defined in `lab2.md` and the lab 2 tutorial in [the developerWorks page](https://developer.ibm.com/courses/all/docker-essentials-extend-your-apps-with-containers) appears to be incorrect. 

Running the python script with `python3 app.py` would return an error : 

```
File "app.py", line 1
    echo 'from flask import Flask
                                ^
SyntaxError: EOL while scanning string literal
```

Possible fix: update the `lab2.md` file in this repo with the copy found at [this forked repo](https://github.com/jzaccone/intro-to-docker-lab/blob/master/lab2.md), and update the tutorial page as well for future students...

**Comment by duglin** [comment]
ping @jzaccone - can you take a look at this?

**Comment by jzaccone** [comment]
I attempted to simplify non-vi users in the play-with-docker environment by providing a one-line command to create the file for them. Also eliminates problems caused by incorrect spacing as can be frustrating sometimes with python.

That whole code block needs to be copy pasted and it creates a python app.py which works. You created a file and copied the echo command into it.

**Comment by doxcom** [comment]
I was using windows and the same issue, my fix was this:
I copy the python code into  IDLE from python

![imagen](https://user-images.githubusercontent.com/49726873/86188876-9b1fbb00-bb05-11ea-87ee-5d139926e7fc.png)
 
then I save it, and delete all the previous docker images of python and execute the app.py from your
command line: 
>python app.py 
and check if the program is running ,it works for me on localhost:5000  (using python command line)
i stopped it and then build the image 
>docker image build -t python-hello-world .
and execute it:
>docker run -p 5001:5000 -d python-hello-world 
and finally check the localhost:5001
