### ISSUE TITLE
Port 5001 not exposed in the Dockerfile

### ISSUE THREAD

**Issue by Bronx205** [IBM/intro-to-docker-lab#3]
You gotta add:
EXPOSE 5001

To your Dockerfile or else you'll get a Refused connection

**Comment by jzaccone** [comment]
From the docker docs: 

> The EXPOSE instruction does not actually publish the port. It functions as a type of documentation between the person who builds the image and the person who runs the container, about which ports are intended to be published. 

EXPOSE is best practice, but not needed
